---
title: "TIF data download UHI and other variables"
author: "Pradnya Raut"
date: "2024-10-11"
output: html_document
---

```{r setup, include=FALSE}
gc()
unlink(tempdir(), recursive = TRUE) 

knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Intall & Load the libraries
```{r message=FALSE}

# Set CRAN mirror
options(repos = "http://cran.us.r-project.org")

# Include the libraries that are needed to be installed
libs <- c(
    "tidyverse", "sf", "geodata",
    "terra",  "dplyr", "utils", 
    "raster", "tibble", "readr"
)

installed_libs <- libs %in% rownames(
    installed.packages()
)

if (any(installed_libs == F)) {
    install.packages(
        libs[!installed_libs]
    )
}

invisible(lapply(
    libs,
    library,
    character.only = T
))

```


# Unzip Cities Shapefile if not present in directory
```{r}
# Define file name and folder path
file_name <- "ne_10m_urban_areas_landscan.shp"
folder_path <- "../data/07_cities_shapefile"

# Check if the file exists in the folder
if (!file.exists(file.path(folder_path, file_name))) {
  # Unzip the file
  unzip(zipfile = file.path(folder_path, "data_EPSG_4326.zip"), exdir = folder_path)
}
```

# Load the cities shapefile
```{r}
file_name <- "ne_10m_urban_areas_landscan.shp"
folder_path <- "../data/07_cities_shapefile"

# Read the shapefile
world_city_map <- st_read(file.path(folder_path, file_name))
```
# City names stored in a list
```{r}
city_names <- unique(world_city_map$name_conve)
city_names_list <- as.list(city_names)

```

# Definition of getContinents() funciton
```{r}
getContinents <- function(city_polys, cont_polys) {
  # Assigns each city to a continent.
  names <- city_polys$name_conve
  continents <- cont_polys$NAME
  cont_list <- rep(NA, nrow(city_polys))
  for (i in 1:nrow(city_polys)) {
    poly <- city_polys$geometry[[i]]
    if (!is.null(poly)) {
      if (!st_is_valid(poly)) {
        poly <- st_buffer(poly, dist = 0)
      }
      center <- st_centroid(poly)
      min_dist <- 999999
      for (j in 1:nrow(cont_polys)) {
        cont_poly <- cont_polys$geometry[[j]]
        d <- st_distance(center, cont_poly)
        if (length(st_intersection(poly, cont_poly)) > 0) {
          cont_list[i] <- continents[j]
          break
        }
        if (d < min_dist) {
          min_dist <- d
          cont_list[i] <- continents[j]
        }
      }
    }
  }
  return(cont_list)
}
```

# Get Continents name for each city
```{r}
# this shape file is already on github. If not: 
# download the "label areas" from:
# url: https://www.naturalearthdata.com/downloads/50m-physical-vectors/50m-physical-labels/
# the downloaded zip file should be inside folder: '09_continents_shapefile'

# Define file name and folder path
file_name <- "ne_50m_geography_regions_polys.shp"
folder_path <- "../data/09_continents_shapefile"

# Check if the file exists in the folder
if (!file.exists(file.path(folder_path, file_name))) {
  # Unzip the file
  unzip(zipfile = file.path(folder_path, "ne_50m_geography_regions_polys.zip"), exdir = folder_path)
}

# Read the shapefile
continents_data <- st_read(file.path(folder_path, file_name))

options(timeout = 5)

# Filter data based on condition
continents_data <- continents_data[continents_data$FEATURECLA == 'Continent', ]

# Call the function
result <- getContinents(world_city_map, continents_data)

options(timeout = 5)

world_city_map$Continent <- result
```




## Open UHI and other Variable files

```{r UHI, echo=FALSE}
terraOptions(verbose=TRUE)
library(terra)
check1 = tryCatch({
  # Open tif file as raster or stack tif files
  open_tif <- function( tif_file, asraster = FALSE){
    if (asraster == TRUE)
      outfl <- terra::rast(tif_file)
    else
      outfl <- stack(tif_file)
    return(outfl) 
    }

ndviprocess <- TRUE #  FALSE # 
s_water_process <- TRUE # FALSE  #

uhi <- open_tif("../data/10_raw_Other_variables/UHI_yearly_pixel_2018.tif") 

surfacewater_list <- list()
if (s_water_process){
  sfiles <- list.files("../data/10_raw_Other_variables/", pattern = ".tif$",
                       all.files= T, full.names= T) 
  nfiles <- list.files("../data/10_raw_Other_variables/NDVI", pattern = ".tif$", 
                       full.names = TRUE) 

  swatercsv = read_csv("../data/10_raw_Other_variables/City_surface.csv") 
  }

if (ndviprocess){
  ndvicsv = read_csv("../data/10_raw_Other_variables/City_NDVI_files.csv") 
  names(ndvicsv)[2] <- "city"
  nfiles <- list.files("../data/10_raw_Other_variables/NDVI", pattern = "*.tif$", 
                       full.names = TRUE)
  nfilelist <-list()
   
}

uhi
uhi_day <- uhi[["Daytime"]]
uhi_night <- uhi[["Nightime"]]

uhi_day
uhi_night

}, error = function(e){
  unlink(tempdir(), recursive = TRUE) 
  gc()
  }, finally = function(f){})

```

## Crop Cities from world map

```{r UHI raster processing, echo=FALSE}
library(tibble)
library(dplyr)
library(terra)
library(sf)
library(readr)
check = tryCatch({
  crop_city <- function(tif_raster, cty_nm){
    city_sf <- world_city_map %>%
      filter(name_conve %in% cty_nm)
    
    city_variable <- terra::crop(  tif_raster, city_sf)
    
  }
      
  city_mean <- function(city_variable){  
    # terra::aggregate to reduce dim
    city_variable_agg <- city_variable |>
      terra::aggregate( fact = 3)
    return(city_variable_agg)
  }
  
  city_meanval <- function(city_variable ){
    mean_df <- colMeans(city_variable, na.rm = TRUE)
    totcol <- ncol( city_variable)

    meancolvalue <- mean_df[totcol][1] # colmn]  #Daytime]

    print( paste0('Mean ', as.character(meancolvalue)) )

    return(meancolvalue)
  }
      
  city_to_df <- function(city_variable, ncolmn){    
    # convert raster data to dataframe
    city_variable_df = as.data.frame(
      city_variable, 
      xy = T, 
      na.rm = T
    )
    head(city_variable_df)
    city_variable_df<- (city_variable_df) %>%
       filter( is.numeric(as.numeric(as.character(city_variable_df$ncolmn) )) )
    # Convert all values to numeric
    city_variable_df[] <- lapply(city_variable_df, function(x)
      as.numeric(as.character(x)))
    # Replace NA values with zero
    city_variable_df[is.na(city_variable_df)] <- 0
    return(city_variable_df)
  }
  
  #Save raster
  save_raster<- function(city_variable, rastername, ctynm=""){
    # Output Folder
    output_folder <- "../data/11_Output_R/city_rasters/"
  
    # Check if the output folder exists, if not, create it
    if (!file.exists(output_folder)) {
      dir.create(output_folder, recursive = TRUE)
    }
    if (ctynm=="")
      cty_nm <- city_name 
  
    # Specify the file path where we want to save the raster
    fl = paste0(ctynm,"_",rastername,".tif", sep = "")
    print( paste0('Raster saved to ', fl))
    output_file <- paste0(output_folder, fl, sep = "" ) #city_name, sep = "")
  
    # Write the raster to a GeoTIFF file
    writeRaster(city_variable, filename = output_file, overwrite = TRUE)
    

  }
  
  Process_other_variable <- function( csvfl, pctyname="", variable_name='S_WATER'){
    
    filteredcsv <- csvfl 
    firstfl <- TRUE
    
    meanvalue <-0
    ncnt<-0
    errmsge <- ""
    fcsv <- ""
    splitcount <- sum(filteredcsv[,2]  == pctyname)      
    meancount <- count(AllvarMean)

    for (rw in rownames(filteredcsv) ){
      if (length(pctyname) >0 ){
        if (!(filteredcsv[rw,2]  == pctyname))
          next
      }
      else
      {
        currct <- filteredcsv[rw,2]
      }
      mean_value <-0
       
      tif_flname <- filteredcsv[rw,4]
      cty <- filteredcsv[rw,2]
      cty2 <- as.character(filteredcsv[rw,2])   # Added as error during add row

      if (ncnt > n)
        break
      
      ncnt <- ncnt+1
      
      city_sf1 <-city_sf   # Added to preserve original city name 

      if (firstfl){
        tiffl <- tif_flname  

        pathfl <- paste0(str_trim('../data/10_raw_Other_variables/'),variable_name,'/',
                         str_trim(tiffl), sep="")
        othvar_raster<- open_tif( pathfl , TRUE)
        
      }
      else
        if (tiffl != tif_flname ){
          tiffl <- tif_flname
          pathfl <- paste0(str_trim('../data/10_raw_Other_variables/'),variable_name,'/',
                          str_trim(tiffl) , sep="")

          othvar_raster<- open_tif( pathfl , TRUE)
          

        }

      chk = tryCatch({
        
        city_othvar <- terra::crop(  othvar_raster, city_sf1)
        pfx = variable_name #"ndvi"
        if (ncnt > 1)
          pfx= paste0( variable_name, as.character(ncnt))
        save_raster(city_othvar, pfx , cty) # save raster

        city_othvar_df <- city_to_df(city_othvar, variable_name)
  
        if (splitcount> 1){
          if (firstfl){
            city_othvar_df0 <- city_othvar_df 
            
            firstfl <- FALSE
          }
          else
          {
            city_othvar_df2 <-  rbind(city_othvar_df0, city_othvar_df)
            city_othvar_df0 <- city_othvar_df2
            city_othvar_df  <- city_othvar_df2
          }
          if (ncnt == splitcount)
            {
            dfcnt <- count(city_othvar_df )
            print('Total Records in dataframe')
            print(dfcnt)
            }
        }
        
        if (ncnt == splitcount){
          head(city_othvar_df)
          mean_value <- city_meanval( city_othvar_df )
        }
        
      }, error = function(e){ 
        mean_value <- -999999999
        firstfl <- FALSE
        print( paste0("Cannot crop city ", pctyname ))
        errmsge <- paste0("cannot crop ",variable_name, ' of ',pctyname, ' ',tiffl)
        Allerror <- Allerror %>%
          add_row( city = cty2,
                   variabl = paste(variable_name, tiffl)
                   )
        return(mean_value)
        })
      
      
      apprec = (counter==0) 
      if (splitcount == ncnt){
        if (variable_name == 'NDVI'){
          AllvarMean <- AllvarMean %>%
            add_row( city = cty2,
                     mean_ndvi = as.numeric(mean_value),
                     err = errmsge  )
        
          nextfivefl <- as.character(nextfive)
          # Save the data frame to a CSV file
  
          write.csv(AllvarMean, paste0(
            "../data/11_Output_R/Citywise Mean ",variable_name, nextfivefl,".csv", sep=""),
            row.names = FALSE)} # , append=TRUE)
        else{
          AllMeanSwater <- AllMeanSwater %>%
            add_row( city = cty2,
                     mean_swater = as.numeric(mean_value),
                     err = errmsge
                   )

          nextfivefl <- as.character(nextfive)
          # Save the data frame to a CSV file
  
          write.csv(AllMeanSwater, paste0(
            "../data/11_Output_R/Citywise Mean Surface water ", nextfivefl,".csv", sep=""),
            row.names = FALSE) # , append=TRUE) 
          }
      }
      firstfl <- FALSE
    }
  return( mean_value)
  }
  
  start.time <- Sys.time()
  nextfive <- 10  #28
  counter <- 0
  steps <- 600 #300
  
  ctystart <- (nextfive* steps)
  ctyend <- (ctystart+ steps )
  n <- ctyend  # 600
  
  # Create the dataframe
  AllCityMeans <- tibble(
    city = character(),
    mean_ndvi = numeric(),
    mean_surface_water  = numeric(),
    mean_uhi_DayNight  = numeric(),
    mean_uhi_daytime = numeric(),
    mean_uhi_Nighttime = numeric()
  )
  meansurfacewater <-0
  meanndvi <-0
  
  AllvarMean <- tibble(
    city = character(),
    mean_ndvi = numeric(),
    err = character()
    )
  AllMeanSwater <- tibble(
    city = character(),
    mean_swater = numeric(),
    err = character()
    )
  Allerror <- tibble(
    city = character(),
    variabl = character()
    )
  
  
  
  Allctylst <-city_names_list
  currcty <- as.list(Allctylst[ctystart:ctyend])

  
# skipping cities due to error
  city_skip_list <- list('Bathurst1', 'Bathurst2', 'DamanhÌÈr', 'DÌùsseldorf', 'JaÌ©n', 
                         'LÌùderitz', 'MÌùnster', 'Cadiz1', 'Cadiz2', 'Newcastle',
                         'Ciudad JuÌÁrez', 'OsnabrÌùck', 'PiraiÌ©vs', 'Saint George‰Ûªs',
                         'San SebastiÌÁn', 'St. John‰Ûªs', 'Ypacarai|Ita')
  for (city_name in city_names_list) {
    if ((counter< ctystart) || (city_name %in% city_skip_list) ){
      counter <- counter +1
      next
    }

    cty_raster <-  city_name   
    print(paste0('UHI data for city ', city_name))
  
    city_sf <- world_city_map %>%
      filter(name_conve %in% city_name)
    
    city_variable <- terra::crop(  uhi_day, city_sf)

    
    city_df <- city_to_df(city_variable, 'daytime')
    print('daytime')    
    head(city_df)
    meanDaytimeval <- city_meanval(city_df )
  
    city_night <- terra::crop(  uhi_night, city_sf)
    city_Night_df <- city_to_df(city_night, 'nighttime')
    print('nighttime')
    head(city_Night_df)
    meanNighttime <- city_meanval(city_Night_df )
      
    city_daynight <- terra::crop(  uhi, city_sf)
    save_raster(city_daynight, "uhi", cty_raster) # save raster
    
    city_dayNight_df <- city_to_df(city_daynight, 'daynight')
    city_dayNight_df$daynight <- ( city_dayNight_df$Daytime + 
      city_dayNight_df$Nightime )
    
    print('Day & night time')    
    head(city_Night_df)
    mean_day_night <- city_meanval( city_dayNight_df )  
    
    if (s_water_process){  
      # Create the dataframe

      errmsge <-""
      meansurfacewater<-  Process_other_variable( swatercsv,  city_name, 'SWATER'  ) 

      if (!is.na(meansurfacewater)){
        if ((meansurfacewater == -999999999))
          {
          meansurfacewater<- 0
          errmsge <- paste0("Error in ",city_name)
        }
      }
      AllMeanSwater <- AllMeanSwater %>%
        add_row( city = city_name ,
                 mean_swater = as.numeric(meansurfacewater),
                 err = errmsge
                 )
      nextfivefl <- as.character(nextfive)
      # Save the data frame to a CSV file

      write.csv(AllMeanSwater, paste0(
        "../data/11_Output_R/Citywise Mean Surface water ",nextfivefl,".csv", sep=""),
        row.names = FALSE) #, append=TRUE)

    }
    
    meanndvi <- 0
    # NDVI processing 
  
    if (ndviprocess){   
      # Create the dataframe

      errmsge <-""
      meanndvi<-  Process_other_variable( ndvicsv,  city_name, 'NDVI'  ) 
      # Process_NDVI( ndvicsv,  city_name    ) #currctylist )
      if (!is.na(meanndvi)){
        if ((meanndvi == -999999999 ))
          {
          meanndvi<- 0
          errmsg <- paste0("Error in ",city_name)
          }
      }
      AllvarMean <- AllvarMean %>%
        add_row( city = city_name ,
                 mean_ndvi = as.numeric(meanndvi),
                 err = errmsge
                 )
      nextfivefl <- as.character(nextfive)
      # Save the data frame to a CSV file
      
      write.csv(AllvarMean, paste0(
        "../data/11_Output_R/Citywise Mean NDVI",nextfivefl,".csv", sep=""),
        row.names = FALSE) #, append=TRUE)
      
      }  
    
    # Add a record to the dataframe
    AllCityMeans <- AllCityMeans %>%
    add_row(
      city = city_name,
      mean_ndvi = meanndvi,
      mean_surface_water = meansurfacewater,
      mean_uhi_DayNight  = mean_day_night,
      mean_uhi_daytime = meanDaytimeval,
      mean_uhi_Nighttime = meanNighttime
    )

    nextfivefl <- as.character(nextfive)
    # Save the data frame to a CSV file
    write.csv(AllCityMeans, paste("../data/11_Output_R/Citywise Means",nextfivefl,".csv"), 
              row.names = TRUE) #, append=TRUE)

    counter <- counter + 1
    if (counter >= n) {
      break  # Break the loop when counter reaches n
    }  
  
    
  
  }
  print(AllvarMean)
  print(AllCityMeans)
  end.time <- Sys.time()
  time.taken <- end.time - start.time
  time.taken
  
  unlink(tempdir(), recursive = TRUE) 
  gc()
  }, finally = function(f){
    unlink(tempdir(), recursive = TRUE) 
    gc()
    })

```

